# Generated by Django 3.1 on 2020-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image_1', upload_to='cmd/%Y/%m/%d'),
        ),
    ]
