# Generated by Django 3.1 on 2020-09-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200907_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image_1', upload_to='cms/%Y/%m/%d'),
        ),
    ]
